### PR TITLE
python 3 compatibility

### PR DESCRIPTION
**Pull request by biodigitals**

### CODE REVIEW

**Comment by biodigitals** [comment]
some code cleaning also

**Comment by encolpe** [comment]
I'm sure i'm missing something very simple but the welcome page doesn't work on a new environment.

My basic setup:

```bash
virtualenv -p /usr/bin/python3.5 venv-apetizer
pip install -e git+https://github.com/biodigitals/apetizer.git@python3#egg=apetizer
./manage.py migrate
./manage.py createsuperuser
./manage.py runserver 127.0.0.1:8001
```

```Python
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8001/view/

Django Version: 1.9.1
Python Version: 3.5.0
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.contenttypes',
 'django.contrib.humanize',
 'django.contrib.messages',
 'django.contrib.sitemaps',
 'django.contrib.staticfiles',
 'markdown_deux',
 'easy_thumbnails',
 'leaflet',
 'apetizer']
Installed Middleware:
['django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'apetizer.middleware.multisite.DynamicSitesMiddleware',
 'apetizer.middleware.multilingual.MultilingualURLMiddleware',
 'apetizer.middleware.redirect.ItemRedirect',
 'apetizer.middleware.profiler.CProfileMiddleware']



Internal Server Error: /view/
Traceback (most recent call last):
  File "/home/edegoute/Venv/venv-apetizer/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/edegoute/Venv/venv-apetizer/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/edegoute/Venv/venv-apetizer/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/edegoute/Venv/venv-apetizer/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/edegoute/Venv/venv-apetizer/src/apetizer/apetizer/views/action.py", line 123, in get
    return self.pre_process(request, input_data, **kwargs)
  File "/home/edegoute/Venv/venv-apetizer/src/apetizer/apetizer/views/user.py", line 86, in pre_process
    return super(UserView, self).pre_process(request, input_data, **kwargs)
  File "/home/edegoute/Venv/venv-apetizer/src/apetizer/apetizer/views/pipe.py", line 148, in pre_process
    response = super(ActionPipeView, self).pre_process(request, input_data, **kwargs)
  File "/home/edegoute/Venv/venv-apetizer/src/apetizer/apetizer/views/action.py", line 365, in pre_process
    return self.process(request, user_profile, input_data, template_args, **kwargs)
  File "/home/edegoute/Venv/venv-apetizer/src/apetizer/apetizer/views/ui.py", line 177, in process
    return super(UIView, self).process(request, user_profile, input_data, template_args, **kwargs)
  File "/home/edegoute/Venv/venv-apetizer/src/apetizer/apetizer/views/content.py", line 190, in process
    return super(ContentView, self).process(request, user_profile, input_data, template_args, **kwargs)
  File "/home/edegoute/Venv/venv-apetizer/src/apetizer/apetizer/views/action.py", line 384, in process
    **kwargs)
  File "/home/edegoute/Venv/venv-apetizer/src/apetizer/apetizer/views/content.py", line 206, in process_view
    return self.render(request, template_args, **kwargs)
  File "/home/edegoute/Venv/venv-apetizer/src/apetizer/apetizer/views/api.py", line 98, in render
    result_status, **kwargs)
  File "/home/edegoute/Venv/venv-apetizer/src/apetizer/apetizer/views/front.py", line 45, in render_html
    template_args['documentation'] = Item.objects.get_at_url('/localhost/')
  File "/home/edegoute/Venv/venv-apetizer/src/apetizer/apetizer/models.py", line 683, in get_at_url
    raise ObjectDoesNotExist()
django.core.exceptions.ObjectDoesNotExist
```

**Comment by biodigitals** [comment]
oh yes .. it's because the /localhost/ item is missing
i made a script gathering code

**Comment by biodigitals** [comment]
thanks encolpe for the py3 motivation !

**Pull request merged**
